### PR TITLE
Bearer token support (using Splunk Token presented in v7.3)

### PR DESCRIPTION
**Pull request by omerl13**
Added support to [Splunk Token](https://docs.splunk.com/Documentation/Splunk/7.3.1/Security/Setupauthenticationwithtokens) presented in version 7.3.

### CODE REVIEW

**Comment by shakeelmohamed** [comment]
@omerl13 thanks for the PR! Unfortunately we won't be able to merge this until we update our CI to test against Splunk 7.3, which is unlikely to happen until after .conf.

We appreciate your patience while we're focusing on other priorities.

**Comment by layertwo** [comment]
Is there any update on this?

**Comment by omerl13** [comment]
@shakeelmohamed can you merge this PR now?

**Comment by omerl13** [comment]
@shakeelmohamed @ljiang1 Is it possible to merge this PR now?

**Comment by shakeelmohamed** [comment]
@omerl13 we are planning to look at this shortly, thank you for your patience

**Pull request merged**
