### PR TITLE
Import module relatively

### PR DESCRIPTION
**Pull request by likel**
I thinks it's a good practise to import internal modules consistently. Now we used relative and absolute import both.

### CODE REVIEW

**Comment by likel** [comment]
The test failure is caused by test environment issue. @shakeelmohamed Could you please take a review at this PR? It's important to us. Happy to hear your comments. Thanks a lot.

**Comment by wjo1212** [comment]
dears, would you please merge the fixing? Thanks!

**Comment by likel** [comment]
Hi @shakeelmohamed ,

Please let me know if you have any other concern. Thanks.

**Comment by shakeelmohamed** [comment]
Closed in favor of #167, we just need to run some manual tests with modular inputs and custom search commands.

**Pull request closed without merging**
