### PR TITLE
Read response before closing connection.

### PR DESCRIPTION
**Pull request by SlaterByte**
Otherwise response.read() is an empty string.

### CODE REVIEW

**Comment by itay** [comment]
@SlaterByte sorry for the delayed response. Could you:

1. Sign the contribution agreement?
2. Rebase this on top of `develop` (and change the target to be `develop`), so that you pick up the Travis CI tests?
3. What version of OS/Python/Splunk were you getting this issue with? I cannot reproduce it, so want to doublecheck.

**Comment by itay** [comment]
@SlaterByte there should be a fix for this in #130 - can you look if it works for you?

**Comment by ukison** [comment]
@itay I am using Mac OS X 10.10.5/Python 2.7.10/Splunk 1.3.1 (1.5.0 is the same), I can't connect to splunk server, because response.read() is an empty string, and this is because the connection is closed before the response.read().
screen shot 2015-12-15 at 12 44 32 pm

**Comment by itay** [comment]
@ukison does the fix in the linked PR work for you?

**Comment by ukison** [comment]
@itay yes, it can fix, thanks.

**Comment by itay** [comment]
Closing this PR as it's been superseded with the other one.

**Pull request closed without merging**
